version: "3.1"

services:
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
    volumes:
      - .:/app

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mike
      POSTGRES_DB: alx
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata:
